<?php

?>
<form id="car_form" method="post" action="<?= $block->getUrl('cars/save') ?>">
    <h1 style="display:inline;">Car Add</h1>

    <hr>
    <label>Car Model</label><input id="car_model" type="text" name="car_model" required/>
    <br />
    <label>Car Manufacturer</label><input id="car_manufacturer" type="text" name="car_manufacturer" required/>
    <br />
    <label>Car Release Year</label><input id="car_release_year" type="text" name="car_release_year" required/>
    <br />
    <label>Car Description</label><input id="car_description" type="text" name="car_description" required/>
    <br />
    <br />
    <br />

    <a href="<?= $block->getUrl('cars') ?>" class="btn_a action-primary">CANCEL</a>
    <input class="action-primary" type="submit" id="Save" name="Save" value="SAVE"/>
</form>
