<?php
/** @var \Voronin\Cars\Block\Template $block */
/** @var $viewModelCars \Voronin\Cars\ViewModel\MyViewModel */
$viewModelCars = $block->getViewModelCars();
$cars = $viewModelCars->getAllCars();
?>

<?php
if (count($cars) > 0): ?>

<table border="1">
    <tr>
        <th><?= __("ID") ?></th>
        <th><?= __("Model") ?></th>
        <th><?= __("Manufacturer") ?></th>
        <th><?= __("Description") ?></th>
        <th><?= __("Release Year") ?></th>
        <th><?= __("Created At") ?></th>
        <th><?= __("Updated At") ?></th>
        <th><?= __("Link to edit") ?></th>
        <th><?= __("Link to delete") ?></th>
    </tr>
    <?php foreach ($cars as $car): ?>
        <tr>
            <td><?= $car->getId() ?></td>
            <td><?= $car->getCarModel() ?></td>
            <td><?= $car->getCarManufacturer() ?></td>
            <td><?= $car->getCarDescription() ?></td>
            <td><?= $car->getCarReleaseYear() ?></td>
            <td><?= $car->getCarCreatedAt() ?></td>
            <td><?= $car->getCarUpdatedAt() ?></td>
            <td><a href="<?= $block->escapeUrl($block->getUrl('cars/edit/index/id/' . $car->getId())) ?>" class="btn_a action primary" style="color: #B2D0F7"><?= __("Edit") ?></a></td>
            <td><a href="<?= $block->escapeUrl($block->getUrl('cars/delete/index/id/' . $car->getId())) ?>" class="btn_a action primary" style="color: black"><?= __("Delete") ?></a></td>
        </tr>
    <?php endforeach; ?>
</table>
    <?php else :?>
    <h1><?= __("This is no car to display.") ?></h1>
<?php endif;?>
    <hr />
<a href="<?= $block->getUrl('cars/add') ?>" class="btn_a action primary">Add car</a>

