<?php
/** @var \Voronin\Cars\Block\Template $block */
//var_dump($block->getAllCars()->getData());
//echo gettype($block->getAllCars());
$cars = $block->getAllCars();
?>

<?php
if (count($cars) > 0): ?>

<table border="1">
    <tr>
        <th><?= __("ID") ?></th>
        <th><?= __("Model") ?></th>
        <th><?= __("Manufacturer") ?></th>
        <th><?= __("Description") ?></th>
        <th><?= __("Release Year") ?></th>
        <th><?= __("Created At") ?></th>
        <th><?= __("Updated At") ?></th>
        <th><?= __("Link to edit") ?></th>
        <th><?= __("Link to delete") ?></th>
    </tr>
    <?php foreach ($cars as $car): ?>
        <tr>
            <td><?= $car->getId() ?></td>
            <td><?= $car->getCarModel() ?></td>
            <td><?= $car->getCarManufacturer() ?></td>
            <td><?= $car->getCarDescription() ?></td>
            <td><?= $car->getCarReleaseYear() ?></td>
            <td><?= $car->getCarCreatedAt() ?></td>
            <td><?= $car->getCarUpdatedAt() ?></td>
            <td><a href="<?= $block->escapeUrl($block->getEditUrl($car->getId())) ?>"><?= __("Edit") ?></a></td>
            <td><a href="<?= $block->escapeUrl($block->getDeleteUrl($car->getId())) ?>"><?= __("Delete") ?></a></td>
        </tr>
    <?php endforeach; ?>
</table>
    <?php else :?>
    <h1><?= __("This is no car to display.") ?></h1>
<?php endif;?>
    <hr />
<a href="<?= $block->getAddUrl()?>" class="btn_a">Add car</a>

